version: "3.3"

services:
  my-mongodb:
    image: mongo
    container_name: mongodb-${NODE_ENV}
    restart: always
    ports:
      - 27000:27000
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
  myapp:
    image: "raquelbatista/myappimage:1.0"
    ports: 
      - 8090:8090
    container_name: "myapp"

volumes:
  mongodb:
  mongoconfig:
