---
-
  name: Install/Update App
  hosts: webservers
  become: yes
  vars:
  - docker_container_name: "myapp"
  - docker_mongo_container_name: "mongodb-"
  - docker_mongo_image_name: "mongo"
  - docker_compose_version: "1.25.0"
  tasks:
    - debug: 
        msg: "Hello Docker"

    - name: "Check if docker is installed"
      shell: command -v docker >/dev/null 2>&1
      register: is_docker_install
      ignore_errors: yes

    - debug: msg="{{is_docker_install}}"

    - name: "Check if docker-compose is installed"
      shell: command -v docker-compose >/dev/null 2>&1
      register: is_docker_compose_install
      ignore_errors: yes

    - debug: msg="{{is_docker_compose_install}}"

    #- name: "Install required system packages"
    #  apt: name={{ item }} state=latest update_cache=yes
    #  loop: [ 'python3-pip', 'python3-setuptools']

    - name: "Add Docker Repository"
      apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present
      when: is_docker_install.rc != 0

    - name: "Update apt and install docker-ce"
      apt: update_cache=yes name=docker-ce state=latest
      when: is_docker_install.rc != 0

    - name: "Install Docker Module for Python"
      pip:
       name: docker
      when: is_docker_install.rc != 0
      
    - name: "Run and enable docker"
      service:
        name: docker
        state: started
        enabled: true


    - name: "Install docker-compose if necessary"
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
        force: yes
      when: is_docker_compose_install.rc != 0

    - name: "Check if already has mongo image"
      docker_image:
         name: "{{docker_mongo_image_name}}"
         tag: "latest"
         state: present
         source: pull

    - name: "Create mongo container if necessary"
      docker_container:
         name: "{{docker_mongo_container_name}}"
         image: "{{docker_mongo_image_name}}"
         ports:
          - "0.0.0.0:27000:27000"
         state: started

    - name: "Stop and Remove all myapp containers"
      docker_container:
         name: "{{docker_container_name}}"
         state: absent

    - name: "Remove myapp Image"
      shell: "docker rmi raquelbatista/myappimage:1.0"
      #ignore_errors: yes
      
    - name: "Pull docker image from DockerHub"
      docker_image:
         name: "raquelbatista/myappimage:1.0"
         tag: "1.0"
         state: present
         source: pull
         
    - name: "Launch docker container"
      docker_container:
         name: "{{docker_container_name}}"
         image: "raquelbatista/myappimage:2.0"
         ports:
          - "127.0.0.1:8090:8090"
         links:
          - "mongodb-:db"
         state: started
      register: docker_info
